"""Initial product catalogue — seeded on startup if collection is empty."""

INITIAL_PRODUCTS = [
    {
        "id": "mln-001",
        "name": "Détecteur de Caméras Cachées",
        "tagline": "Voyage discret. Confiance absolue.",
        "category": "curios",
        "price": 89,
        "compare_at": 129,
        "is_new": True,
        "best_seller": True,
        "description": "Scanner infrarouge de poche. Détecte objectifs et signaux RF dans les hôtels, locations courtes durées et bureaux. Boîtier aluminium brossé, autonomie 14h.",
        "images": [
            "https://images.unsplash.com/photo-1595303526913-c7037797ebe7",
            "https://images.unsplash.com/photo-1615655406736-b37c4fabf923",
        ],
        "specs": ["Aluminium CNC", "USB-C — 14h", "Portée 8 m", "Mode silencieux"],
    },
    {
        "id": "mln-002",
        "name": "Ampoule MALIN E27 — Adaptive",
        "tagline": "Lumière qui pense.",
        "category": "smart-home",
        "price": 39,
        "compare_at": None,
        "is_new": True,
        "best_seller": False,
        "description": "Ampoule connectée à température adaptive. S'accorde à l'heure du jour et à votre rythme. Pilotable via Wi-Fi, Matter et HomeKit.",
        "images": [
            "https://images.pexels.com/photos/5208869/pexels-photo-5208869.jpeg",
            "https://images.unsplash.com/photo-1615655406736-b37c4fabf923",
        ],
        "specs": ["E27 — 9W", "Matter / HomeKit", "1800K – 6500K", "16M couleurs"],
    },
    {
        "id": "mln-003",
        "name": "Couteau Hokkaido Slim",
        "tagline": "Acier japonais. Geste précis.",
        "category": "cuisine",
        "price": 145,
        "compare_at": None,
        "is_new": False,
        "best_seller": True,
        "description": "Lame VG-10 forgée 67 couches, manche pakkawood. Une seule lame, pour tout le quotidien. Édition numérotée.",
        "images": [
            "https://images.unsplash.com/photo-1778049692415-736a34626d9a",
            "https://images.unsplash.com/photo-1615655406736-b37c4fabf923",
        ],
        "specs": ["VG-10 — 60 HRC", "21 cm", "Pakkawood", "Numérotée"],
    },
    {
        "id": "mln-004",
        "name": "Machine Espresso Type-01",
        "tagline": "Rituel du matin, redéfini.",
        "category": "cuisine",
        "price": 489,
        "compare_at": 599,
        "is_new": False,
        "best_seller": True,
        "description": "Pompe italienne 15 bars, mousseur lait pro, finition céramique mate. Conçue pour durer une décennie.",
        "images": [
            "https://images.unsplash.com/photo-1769326541255-c6612ab334a0",
            "https://images.unsplash.com/photo-1615655406736-b37c4fabf923",
        ],
        "specs": ["15 bars", "Mousseur pro", "Céramique mate", "Garantie 5 ans"],
    },
    {
        "id": "mln-005",
        "name": "Hoodie MALIN Heavyweight",
        "tagline": "Coton brut. Coupe carrée.",
        "category": "habillement",
        "price": 165,
        "compare_at": None,
        "is_new": True,
        "best_seller": False,
        "description": "Coton 460gsm, teinture pigment, broderie tonale. Coupe boxy, capuche double épaisseur. Produit au Portugal.",
        "images": [
            "https://images.pexels.com/photos/11317811/pexels-photo-11317811.jpeg",
            "https://images.pexels.com/photos/29548609/pexels-photo-29548609.jpeg",
        ],
        "specs": ["Coton 460gsm", "Portugal", "Teinture pigment", "Boxy fit"],
    },
    {
        "id": "mln-006",
        "name": "Sweat Capuche — Encre",
        "tagline": "Le noir qui ne déteint pas.",
        "category": "habillement",
        "price": 145,
        "compare_at": None,
        "is_new": False,
        "best_seller": False,
        "description": "Hoodie unisexe. Doublure brossée, cordons métalliques. Teinture résistante 50 lavages garantis.",
        "images": [
            "https://images.pexels.com/photos/29548609/pexels-photo-29548609.jpeg",
            "https://images.unsplash.com/photo-1559697242-a465f2578a95",
        ],
        "specs": ["Unisexe", "Brossé intérieur", "Cordons métal", "50 lavages"],
    },
    {
        "id": "mln-007",
        "name": "Manette Gaming Pro — Onyx",
        "tagline": "Pour ceux qui ne ratent pas.",
        "category": "tech-gaming",
        "price": 219,
        "compare_at": 259,
        "is_new": True,
        "best_seller": True,
        "description": "Gâchettes Hall Effect, sticks magnétiques, latence sub-1ms. Compatible PC, consoles et mobile.",
        "images": [
            "https://images.unsplash.com/photo-1615655406736-b37c4fabf923",
            "https://images.pexels.com/photos/5208869/pexels-photo-5208869.jpeg",
        ],
        "specs": ["Hall Effect", "Latence <1ms", "Multi-plateforme", "USB-C"],
    },
    {
        "id": "mln-008",
        "name": "Casque VR Compact",
        "tagline": "L'évasion en 280g.",
        "category": "tech-gaming",
        "price": 449,
        "compare_at": None,
        "is_new": False,
        "best_seller": False,
        "description": "Pancake lenses, 4K par œil, suivi inside-out. Le casque le plus léger de sa catégorie.",
        "images": [
            "https://images.pexels.com/photos/5208869/pexels-photo-5208869.jpeg",
            "https://images.unsplash.com/photo-1615655406736-b37c4fabf923",
        ],
        "specs": ["4K / œil", "280g", "120Hz", "Tracking 6DoF"],
    },
    {
        "id": "mln-009",
        "name": "Carnet Numérique E-Ink",
        "tagline": "Le papier rechargé.",
        "category": "numerique",
        "price": 329,
        "compare_at": None,
        "is_new": True,
        "best_seller": False,
        "description": "Liseuse + tablette d'écriture E-Ink 10.3″. Synchronisation Cloud, stylet inclus. Trois semaines d'autonomie.",
        "images": [
            "https://images.unsplash.com/photo-1468495244123-6c6c332eeece",
            "https://images.unsplash.com/photo-1595303526913-c7037797ebe7",
        ],
        "specs": ["E-Ink 10.3\"", "Stylet inclus", "3 semaines", "Cloud sync"],
    },
    {
        "id": "mln-010",
        "name": "Pack Sons Curatés — Vol.1",
        "tagline": "200 samples. Zéro filler.",
        "category": "numerique",
        "price": 49,
        "compare_at": 89,
        "is_new": False,
        "best_seller": False,
        "description": "Banque de sons produite avec des producteurs indépendants. Licence commerciale incluse. Téléchargement immédiat.",
        "images": [
            "https://images.unsplash.com/photo-1595303526913-c7037797ebe7",
            "https://images.unsplash.com/photo-1615655406736-b37c4fabf923",
        ],
        "specs": ["200 samples", "WAV 24-bit", "Licence commerciale", "Digital"],
    },
    {
        "id": "mln-011",
        "name": "iPhone 13 Pro — Recertifié",
        "tagline": "Reconditionné. Pas dégradé.",
        "category": "occasion",
        "price": 549,
        "compare_at": 899,
        "is_new": False,
        "best_seller": True,
        "description": "Inspecté 41 points, batterie neuve, garantie 12 mois. 256 Go, Graphite. Boîte MALIN recyclée incluse.",
        "images": [
            "https://images.unsplash.com/photo-1468495244123-6c6c332eeece",
            "https://images.unsplash.com/photo-1595303526913-c7037797ebe7",
        ],
        "specs": ["256 Go", "Batterie neuve", "Garantie 12 mois", "Grade A"],
    },
    {
        "id": "mln-012",
        "name": "Mini Frigo Studio — Crème",
        "tagline": "Petit. Silencieux. Beau.",
        "category": "occasion",
        "price": 189,
        "compare_at": 269,
        "is_new": False,
        "best_seller": False,
        "description": "Frigo compact d'occasion sélectionné. Classe A, 18 dB, finition crème. Idéal studio ou bureau.",
        "images": [
            "https://images.unsplash.com/photo-1769326541255-c6612ab334a0",
            "https://images.unsplash.com/photo-1615655406736-b37c4fabf923",
        ],
        "specs": ["Classe A", "18 dB", "85L", "Garantie 6 mois"],
    },
    {
        "id": "mln-013",
        "name": "Capteur de Présence Air",
        "tagline": "Sait quand vous arrivez.",
        "category": "smart-home",
        "price": 79,
        "compare_at": None,
        "is_new": True,
        "best_seller": False,
        "description": "Capteur mmWave compact. Détecte la présence sans bouger un cil. Intégration Matter, Home Assistant.",
        "images": [
            "https://images.pexels.com/photos/5208869/pexels-photo-5208869.jpeg",
            "https://images.unsplash.com/photo-1615655406736-b37c4fabf923",
        ],
        "specs": ["mmWave 60GHz", "Matter", "USB-C", "Sans bouger"],
    },
    {
        "id": "mln-014",
        "name": "Briquet Tempête Brossé",
        "tagline": "Objet rituel.",
        "category": "curios",
        "price": 59,
        "compare_at": None,
        "is_new": False,
        "best_seller": False,
        "description": "Briquet à arc électrique rechargeable. Coupe-vent. Boîtier acier brossé, gravure profonde.",
        "images": [
            "https://images.unsplash.com/photo-1615655406736-b37c4fabf923",
            "https://images.unsplash.com/photo-1595303526913-c7037797ebe7",
        ],
        "specs": ["Arc électrique", "USB-C", "Acier brossé", "Coupe-vent"],
    },
]
